
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.cum.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.cum.item.TutaItem;
import net.mcreator.cum.item.TreDiQuadriItem;
import net.mcreator.cum.item.TreDiPicchieItem;
import net.mcreator.cum.item.TreDiFioriItem;
import net.mcreator.cum.item.TreDiCuoriItem;
import net.mcreator.cum.item.TerpeneItem;
import net.mcreator.cum.item.TelefonoItem;
import net.mcreator.cum.item.TecnologiaV1nanteItem;
import net.mcreator.cum.item.StraysArmItem;
import net.mcreator.cum.item.StivaliImmovibiliItem;
import net.mcreator.cum.item.StellaPericolosaItem;
import net.mcreator.cum.item.StellaDelGodoNegativaItem;
import net.mcreator.cum.item.StellaDelGodoItem;
import net.mcreator.cum.item.StaffaDelGodoNegativaItem;
import net.mcreator.cum.item.StaffaDelGodoItem;
import net.mcreator.cum.item.SpadaSuperGodevoleItem;
import net.mcreator.cum.item.SpadaLunare4Item;
import net.mcreator.cum.item.SpadaLunare3Item;
import net.mcreator.cum.item.SpadaLunare2Item;
import net.mcreator.cum.item.SpadaLunare1Item;
import net.mcreator.cum.item.SpadaGodevoleItem;
import net.mcreator.cum.item.SpadaGabriellanteItem;
import net.mcreator.cum.item.SoulSurvivorItem;
import net.mcreator.cum.item.SiItem;
import net.mcreator.cum.item.SetteDiQuadriItem;
import net.mcreator.cum.item.SetteDiPicchieItem;
import net.mcreator.cum.item.SetteDiFioriItem;
import net.mcreator.cum.item.SetteDiCuoriItem;
import net.mcreator.cum.item.SeiDiQuadriItem;
import net.mcreator.cum.item.SeiDiPicchieItem;
import net.mcreator.cum.item.SeiDiFioriItem;
import net.mcreator.cum.item.SeiDiCuoriItem;
import net.mcreator.cum.item.ScheggiaDiPietraBalatranteItem;
import net.mcreator.cum.item.RelazioneVuotaItem;
import net.mcreator.cum.item.RelazioneItem;
import net.mcreator.cum.item.RedCumItem;
import net.mcreator.cum.item.ReceiptItem;
import net.mcreator.cum.item.QuDiQuadriItem;
import net.mcreator.cum.item.QuDiPicchieItem;
import net.mcreator.cum.item.QuDiFioriItem;
import net.mcreator.cum.item.QuDiCuoriItem;
import net.mcreator.cum.item.QUESTOEILGODONegativoItem;
import net.mcreator.cum.item.QUESTOEILGODOItem;
import net.mcreator.cum.item.PuntalenegativoItem;
import net.mcreator.cum.item.PuntaleItem;
import net.mcreator.cum.item.PuntaleContaminatoNegativoItem;
import net.mcreator.cum.item.PuntaleContaminatoItem;
import net.mcreator.cum.item.ProseccoItem;
import net.mcreator.cum.item.PlasmidevuotoItem;
import net.mcreator.cum.item.PlasmidecontetItem;
import net.mcreator.cum.item.PlasmideampItem;
import net.mcreator.cum.item.PerkeoNegativoItem;
import net.mcreator.cum.item.PerkeoItem;
import net.mcreator.cum.item.PeneItem;
import net.mcreator.cum.item.PeneDuroItem;
import net.mcreator.cum.item.PeneDellaFrenesiaItem;
import net.mcreator.cum.item.PaneIntegraleItem;
import net.mcreator.cum.item.PaneDerivanteItem;
import net.mcreator.cum.item.PallottoladoroItem;
import net.mcreator.cum.item.PBR32Item;
import net.mcreator.cum.item.OttoDiQuadriItem;
import net.mcreator.cum.item.OttoDiPicchieItem;
import net.mcreator.cum.item.OttoDiFioriItem;
import net.mcreator.cum.item.OttoDiCuoriItem;
import net.mcreator.cum.item.OggettoNeutroItem;
import net.mcreator.cum.item.OggettoInsicuroItem;
import net.mcreator.cum.item.OcchioMaledettoItem;
import net.mcreator.cum.item.NoveDiQuadriItem;
import net.mcreator.cum.item.NoveDiPicchieItem;
import net.mcreator.cum.item.NoveDiFioriItem;
import net.mcreator.cum.item.NoveDiCuoriItem;
import net.mcreator.cum.item.NoItem;
import net.mcreator.cum.item.NeroColtelloItem;
import net.mcreator.cum.item.MoltItem;
import net.mcreator.cum.item.MicropipettaItem;
import net.mcreator.cum.item.ManoDiMaleniaItem;
import net.mcreator.cum.item.MacchinaDelTempoItem;
import net.mcreator.cum.item.LunaDelGodoItem;
import net.mcreator.cum.item.LingottoUltrakillanteItem;
import net.mcreator.cum.item.JokerItem;
import net.mcreator.cum.item.IndicatoreAlCavoloRossoItem;
import net.mcreator.cum.item.ImpenetrableTemplateItem;
import net.mcreator.cum.item.ImpenetrabileIntermedioItem;
import net.mcreator.cum.item.IlFuMattiaPascalDiscoItem;
import net.mcreator.cum.item.IMPENETRAZIONEItem;
import net.mcreator.cum.item.ILGODOItem;
import net.mcreator.cum.item.GenetetracillinaItem;
import net.mcreator.cum.item.GenesgunItem;
import net.mcreator.cum.item.GeneampicillinaItem;
import net.mcreator.cum.item.GelDiAgarosioItem;
import net.mcreator.cum.item.FrenziedCumItem;
import net.mcreator.cum.item.FrammentoDiVetroItem;
import net.mcreator.cum.item.FireballStrayItem;
import net.mcreator.cum.item.FicheItem;
import net.mcreator.cum.item.EnergiaItem;
import net.mcreator.cum.item.EctoplasmaNegativoItem;
import net.mcreator.cum.item.EctoplasmaItem;
import net.mcreator.cum.item.EcoRIItem;
import net.mcreator.cum.item.DueDiQuadriItem;
import net.mcreator.cum.item.DueDiPicchieItem;
import net.mcreator.cum.item.DueDiFioriItem;
import net.mcreator.cum.item.DueDiCuoriItem;
import net.mcreator.cum.item.DispositivoTeletrasportanteItem;
import net.mcreator.cum.item.DispositivoNeutralizzanteItem;
import net.mcreator.cum.item.DiscWar2Item;
import net.mcreator.cum.item.DiscWar1Item;
import net.mcreator.cum.item.DiscPandemoniumItem;
import net.mcreator.cum.item.DiscOrder2Item;
import net.mcreator.cum.item.DiscOrder1Item;
import net.mcreator.cum.item.DiscChaosItem;
import net.mcreator.cum.item.DimensioneSullaSicurezzaItem;
import net.mcreator.cum.item.DimensionePericolanteItem;
import net.mcreator.cum.item.DieciDiQuadriItem;
import net.mcreator.cum.item.DieciDiPicchieItem;
import net.mcreator.cum.item.DieciDiFioriItem;
import net.mcreator.cum.item.DieciDiCuoriItem;
import net.mcreator.cum.item.DNAItem;
import net.mcreator.cum.item.DNAFrammentatoItem;
import net.mcreator.cum.item.CuboItem;
import net.mcreator.cum.item.ConoItemItem;
import net.mcreator.cum.item.ClonatoreItem;
import net.mcreator.cum.item.CipollaMarciaItem;
import net.mcreator.cum.item.CinDiQuadriItem;
import net.mcreator.cum.item.CinDiPicchieItem;
import net.mcreator.cum.item.CinDiFioriItem;
import net.mcreator.cum.item.CinDiCuoriItem;
import net.mcreator.cum.item.CianografiaNegativaItem;
import net.mcreator.cum.item.CianografiaItem;
import net.mcreator.cum.item.CcumItem;
import net.mcreator.cum.item.CazzoRottoItem;
import net.mcreator.cum.item.CazzoRossoRottoItem;
import net.mcreator.cum.item.CazzoRossoItem;
import net.mcreator.cum.item.CartaDiPietraItem;
import net.mcreator.cum.item.CampioneDiDNAItem;
import net.mcreator.cum.item.CampioneDiDNAFrammentatoItem;
import net.mcreator.cum.item.BologneseConLUovoItem;
import net.mcreator.cum.item.BlueOrbItem;
import net.mcreator.cum.item.BloodItem;
import net.mcreator.cum.item.BatteriaItem;
import net.mcreator.cum.item.BastonePaperoneItem;
import net.mcreator.cum.item.AssoMultiusoItem;
import net.mcreator.cum.item.AssoDiQuadriItem;
import net.mcreator.cum.item.AssoDiPicchieNegativoItem;
import net.mcreator.cum.item.AssoDiFioriItem;
import net.mcreator.cum.item.AssoDiFioriDiVetroItem;
import net.mcreator.cum.item.AssoDiCuoriItem;
import net.mcreator.cum.item.AssoDiCuoriDiVetroItem;
import net.mcreator.cum.item.ArmaturadelsangueItem;
import net.mcreator.cum.item.ArmaturaUltrakillanteItem;
import net.mcreator.cum.item.ArmaturaLunareItem;
import net.mcreator.cum.item.ArmaturaDelGodoItem;
import net.mcreator.cum.item.AltPiercerItem;
import net.mcreator.cum.item.AlessandroManzoniUovoItem;
import net.mcreator.cum.item.AcquaDelGodoItem;
import net.mcreator.cum.CumMod;

public class CumModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, CumMod.MODID);
	public static final RegistryObject<Item> BLOCCO_DI_SBORRA = block(CumModBlocks.BLOCCO_DI_SBORRA);
	public static final RegistryObject<Item> STELLA_DEL_GODO = REGISTRY.register("stella_del_godo", () -> new StellaDelGodoItem());
	public static final RegistryObject<Item> BLOCCO_PERICOLANTE = block(CumModBlocks.BLOCCO_PERICOLANTE);
	public static final RegistryObject<Item> SPADA_GODEVOLE = REGISTRY.register("spada_godevole", () -> new SpadaGodevoleItem());
	public static final RegistryObject<Item> SPADA_SUPER_GODEVOLE = REGISTRY.register("spada_super_godevole", () -> new SpadaSuperGodevoleItem());
	public static final RegistryObject<Item> BLOCCO_PERICOLOSO = block(CumModBlocks.BLOCCO_PERICOLOSO);
	public static final RegistryObject<Item> BLOCCO_MEDIO = block(CumModBlocks.BLOCCO_MEDIO);
	public static final RegistryObject<Item> ILGODO = REGISTRY.register("ilgodo", () -> new ILGODOItem());
	public static final RegistryObject<Item> DIMENSIONE_PERICOLANTE = REGISTRY.register("dimensione_pericolante", () -> new DimensionePericolanteItem());
	public static final RegistryObject<Item> ASSO_DI_CUORI = REGISTRY.register("asso_di_cuori", () -> new AssoDiCuoriItem());
	public static final RegistryObject<Item> PENE = REGISTRY.register("pene", () -> new PeneItem());
	public static final RegistryObject<Item> CCUM = REGISTRY.register("ccum", () -> new CcumItem());
	public static final RegistryObject<Item> BLOCCO_DI_CARNE = block(CumModBlocks.BLOCCO_DI_CARNE);
	public static final RegistryObject<Item> PENE_DURO = REGISTRY.register("pene_duro", () -> new PeneDuroItem());
	public static final RegistryObject<Item> DI_FAZIO_SPAWN_EGG = REGISTRY.register("di_fazio_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.DI_FAZIO, -13421569, -10079488, new Item.Properties()));
	public static final RegistryObject<Item> BEKER = block(CumModBlocks.BEKER);
	public static final RegistryObject<Item> FRAMMENTO_DI_VETRO = REGISTRY.register("frammento_di_vetro", () -> new FrammentoDiVetroItem());
	public static final RegistryObject<Item> NO = REGISTRY.register("no", () -> new NoItem());
	public static final RegistryObject<Item> SI = REGISTRY.register("si", () -> new SiItem());
	public static final RegistryObject<Item> RELAZIONE = REGISTRY.register("relazione", () -> new RelazioneItem());
	public static final RegistryObject<Item> CAVOLO_ROSSO = block(CumModBlocks.CAVOLO_ROSSO);
	public static final RegistryObject<Item> PALO = block(CumModBlocks.PALO);
	public static final RegistryObject<Item> ATTPED = block(CumModBlocks.ATTPED);
	public static final RegistryObject<Item> ATTCICL = block(CumModBlocks.ATTCICL);
	public static final RegistryObject<Item> VELOCCONSEXTRA = block(CumModBlocks.VELOCCONSEXTRA);
	public static final RegistryObject<Item> VELOCCONSAUTO = block(CumModBlocks.VELOCCONSAUTO);
	public static final RegistryObject<Item> DIVTRANS = block(CumModBlocks.DIVTRANS);
	public static final RegistryObject<Item> SENSO_VIETATO = block(CumModBlocks.SENSO_VIETATO);
	public static final RegistryObject<Item> LIMMAX = block(CumModBlocks.LIMMAX);
	public static final RegistryObject<Item> DIVTRANS_PED = block(CumModBlocks.DIVTRANS_PED);
	public static final RegistryObject<Item> BLOCCO_DI_SANGUE = block(CumModBlocks.BLOCCO_DI_SANGUE);
	public static final RegistryObject<Item> DIV_DI_FER = block(CumModBlocks.DIV_DI_FER);
	public static final RegistryObject<Item> DIV_DI_SOS = block(CumModBlocks.DIV_DI_SOS);
	public static final RegistryObject<Item> DIV_DI_SOR = block(CumModBlocks.DIV_DI_SOR);
	public static final RegistryObject<Item> DIV_DI_SOR_MAG = block(CumModBlocks.DIV_DI_SOR_MAG);
	public static final RegistryObject<Item> DIVTRANSMAG = block(CumModBlocks.DIVTRANSMAG);
	public static final RegistryObject<Item> DIVTRANSPUBBL = block(CumModBlocks.DIVTRANSPUBBL);
	public static final RegistryObject<Item> ASSO_DI_QUADRI = REGISTRY.register("asso_di_quadri", () -> new AssoDiQuadriItem());
	public static final RegistryObject<Item> SENSO_UNICO_FRONTALE = block(CumModBlocks.SENSO_UNICO_FRONTALE);
	public static final RegistryObject<Item> DIR_OBB_DRIT = block(CumModBlocks.DIR_OBB_DRIT);
	public static final RegistryObject<Item> DIR_OBB_DX = block(CumModBlocks.DIR_OBB_DX);
	public static final RegistryObject<Item> DIR_OBB_SX = block(CumModBlocks.DIR_OBB_SX);
	public static final RegistryObject<Item> PASS_OBB_DX = block(CumModBlocks.PASS_OBB_DX);
	public static final RegistryObject<Item> PASS_OBB_SX = block(CumModBlocks.PASS_OBB_SX);
	public static final RegistryObject<Item> INIZIO_VER = block(CumModBlocks.INIZIO_VER);
	public static final RegistryObject<Item> CONTINUAZIONE_VER = block(CumModBlocks.CONTINUAZIONE_VER);
	public static final RegistryObject<Item> FINE_VER = block(CumModBlocks.FINE_VER);
	public static final RegistryObject<Item> INIZIO_OR = block(CumModBlocks.INIZIO_OR);
	public static final RegistryObject<Item> CONTINUO_OR = block(CumModBlocks.CONTINUO_OR);
	public static final RegistryObject<Item> FINE_OR = block(CumModBlocks.FINE_OR);
	public static final RegistryObject<Item> INDICATORE_AL_CAVOLO_ROSSO = REGISTRY.register("indicatore_al_cavolo_rosso", () -> new IndicatoreAlCavoloRossoItem());
	public static final RegistryObject<Item> MIRABELLA_SPAWN_EGG = REGISTRY.register("mirabella_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.MIRABELLA, -6710785, -65536, new Item.Properties()));
	public static final RegistryObject<Item> V_1_SPAWN_EGG = REGISTRY.register("v_1_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.V_1, -16777063, -256, new Item.Properties()));
	public static final RegistryObject<Item> PERICOLANTE_1_SPAWN_EGG = REGISTRY.register("pericolante_1_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.PERICOLANTE_1, -3355648, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> PERICOLANTE_2_SPAWN_EGG = REGISTRY.register("pericolante_2_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.PERICOLANTE_2, -6711040, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> PERICOLANTE_3_SPAWN_EGG = REGISTRY.register("pericolante_3_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.PERICOLANTE_3, -39424, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> OCCHIO_MALEDETTO = REGISTRY.register("occhio_maledetto", () -> new OcchioMaledettoItem());
	public static final RegistryObject<Item> DISPOSITIVO_NEUTRALIZZANTE = REGISTRY.register("dispositivo_neutralizzante", () -> new DispositivoNeutralizzanteItem());
	public static final RegistryObject<Item> ASSO_DI_FIORI = REGISTRY.register("asso_di_fiori", () -> new AssoDiFioriItem());
	public static final RegistryObject<Item> ARMATURA_DEL_GODO_HELMET = REGISTRY.register("armatura_del_godo_helmet", () -> new ArmaturaDelGodoItem.Helmet());
	public static final RegistryObject<Item> ARMATURA_DEL_GODO_CHESTPLATE = REGISTRY.register("armatura_del_godo_chestplate", () -> new ArmaturaDelGodoItem.Chestplate());
	public static final RegistryObject<Item> ARMATURA_DEL_GODO_LEGGINGS = REGISTRY.register("armatura_del_godo_leggings", () -> new ArmaturaDelGodoItem.Leggings());
	public static final RegistryObject<Item> ARMATURA_DEL_GODO_BOOTS = REGISTRY.register("armatura_del_godo_boots", () -> new ArmaturaDelGodoItem.Boots());
	public static final RegistryObject<Item> PERICOLANTE_4_SPAWN_EGG = REGISTRY.register("pericolante_4_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.PERICOLANTE_4, -39424, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> PERICOLANTE_5_SPAWN_EGG = REGISTRY.register("pericolante_5_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.PERICOLANTE_5, -3407872, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> ASSO_MULTIUSO = REGISTRY.register("asso_multiuso", () -> new AssoMultiusoItem());
	public static final RegistryObject<Item> BLOCCO_SICURO = block(CumModBlocks.BLOCCO_SICURO);
	public static final RegistryObject<Item> BLOCCO_NON_SICURO = block(CumModBlocks.BLOCCO_NON_SICURO);
	public static final RegistryObject<Item> BLOCCO_NEUTRO = block(CumModBlocks.BLOCCO_NEUTRO);
	public static final RegistryObject<Item> OGGETTO_NEUTRO = REGISTRY.register("oggetto_neutro", () -> new OggettoNeutroItem());
	public static final RegistryObject<Item> DIMENSIONE_SULLA_SICUREZZA = REGISTRY.register("dimensione_sulla_sicurezza", () -> new DimensioneSullaSicurezzaItem());
	public static final RegistryObject<Item> BLOCCO_PERICOLANTE_NEGATIVO = block(CumModBlocks.BLOCCO_PERICOLANTE_NEGATIVO);
	public static final RegistryObject<Item> ECTOPLASMA = REGISTRY.register("ectoplasma", () -> new EctoplasmaItem());
	public static final RegistryObject<Item> ECTOPLASMA_NEGATIVO = REGISTRY.register("ectoplasma_negativo", () -> new EctoplasmaNegativoItem());
	public static final RegistryObject<Item> STELLA_DEL_GODO_NEGATIVA = REGISTRY.register("stella_del_godo_negativa", () -> new StellaDelGodoNegativaItem());
	public static final RegistryObject<Item> STAFFA_DEL_GODO = REGISTRY.register("staffa_del_godo", () -> new StaffaDelGodoItem());
	public static final RegistryObject<Item> STAFFA_DEL_GODO_NEGATIVA = REGISTRY.register("staffa_del_godo_negativa", () -> new StaffaDelGodoNegativaItem());
	public static final RegistryObject<Item> CAZZO_ROTTO = REGISTRY.register("cazzo_rotto", () -> new CazzoRottoItem());
	public static final RegistryObject<Item> BLOCCO_MEDIO_NEGATIVO = block(CumModBlocks.BLOCCO_MEDIO_NEGATIVO);
	public static final RegistryObject<Item> BLOCCO_PERICOLOSO_NEGATIVO = block(CumModBlocks.BLOCCO_PERICOLOSO_NEGATIVO);
	public static final RegistryObject<Item> ASSO_DI_PICCHIE_NEGATIVO = REGISTRY.register("asso_di_picchie_negativo", () -> new AssoDiPicchieNegativoItem());
	public static final RegistryObject<Item> CAZZO_ROSSO = REGISTRY.register("cazzo_rosso", () -> new CazzoRossoItem());
	public static final RegistryObject<Item> CAZZO_ROSSO_ROTTO = REGISTRY.register("cazzo_rosso_rotto", () -> new CazzoRossoRottoItem());
	public static final RegistryObject<Item> RED_CUM = REGISTRY.register("red_cum", () -> new RedCumItem());
	public static final RegistryObject<Item> BLOCCO_DI_SBORRA_ROSSA = block(CumModBlocks.BLOCCO_DI_SBORRA_ROSSA);
	public static final RegistryObject<Item> BLOCCO_D_ERBA_VUOTO = block(CumModBlocks.BLOCCO_D_ERBA_VUOTO);
	public static final RegistryObject<Item> TELEFONO = REGISTRY.register("telefono", () -> new TelefonoItem());
	public static final RegistryObject<Item> TERRA_VUOTA = block(CumModBlocks.TERRA_VUOTA);
	public static final RegistryObject<Item> RELAZIONE_VUOTA = REGISTRY.register("relazione_vuota", () -> new RelazioneVuotaItem());
	public static final RegistryObject<Item> PIETRA_VUOTA = block(CumModBlocks.PIETRA_VUOTA);
	public static final RegistryObject<Item> BLOCCO_DI_DIAMANTE_VUOTO = block(CumModBlocks.BLOCCO_DI_DIAMANTE_VUOTO);
	public static final RegistryObject<Item> PERICOLANTE_VUOTO = block(CumModBlocks.PERICOLANTE_VUOTO);
	public static final RegistryObject<Item> BATTERIA = REGISTRY.register("batteria", () -> new BatteriaItem());
	public static final RegistryObject<Item> ENERGIA = REGISTRY.register("energia", () -> new EnergiaItem());
	public static final RegistryObject<Item> KILLER_SPAWN_EGG = REGISTRY.register("killer_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.KILLER, -16777216, -15987700, new Item.Properties()));
	public static final RegistryObject<Item> RECEIPT = REGISTRY.register("receipt", () -> new ReceiptItem());
	public static final RegistryObject<Item> GENERATORE = block(CumModBlocks.GENERATORE);
	public static final RegistryObject<Item> V_2_SPAWN_EGG = REGISTRY.register("v_2_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.V_2, -65536, -256, new Item.Properties()));
	public static final RegistryObject<Item> PERICOLANTE_6_SPAWN_EGG = REGISTRY.register("pericolante_6_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.PERICOLANTE_6, -3407872, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> PERICOLANTE_7_SPAWN_EGG = REGISTRY.register("pericolante_7_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.PERICOLANTE_7, -16777216, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> BLOCCO_DI_CARNE_VIVENTE = block(CumModBlocks.BLOCCO_DI_CARNE_VIVENTE);
	public static final RegistryObject<Item> BLOCCO_PERICOLANTE_INVERSO = block(CumModBlocks.BLOCCO_PERICOLANTE_INVERSO);
	public static final RegistryObject<Item> BLOCCO_MEDIO_INVERSO = block(CumModBlocks.BLOCCO_MEDIO_INVERSO);
	public static final RegistryObject<Item> BLOCCO_PERICOLOSO_INVERSO = block(CumModBlocks.BLOCCO_PERICOLOSO_INVERSO);
	public static final RegistryObject<Item> BLOCCO_INSICURO = block(CumModBlocks.BLOCCO_INSICURO);
	public static final RegistryObject<Item> OGGETTO_INSICURO = REGISTRY.register("oggetto_insicuro", () -> new OggettoInsicuroItem());
	public static final RegistryObject<Item> ALESSANDRO_MANZONI_UOVO = REGISTRY.register("alessandro_manzoni_uovo", () -> new AlessandroManzoniUovoItem());
	public static final RegistryObject<Item> SISYPHUS_PRIME_SPAWN_EGG = REGISTRY.register("sisyphus_prime_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.SISYPHUS_PRIME, -39424, -65536, new Item.Properties()));
	public static final RegistryObject<Item> BLOCCO_VIRIDAE = block(CumModBlocks.BLOCCO_VIRIDAE);
	public static final RegistryObject<Item> VIRUS_SPAWN_EGG = REGISTRY.register("virus_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.VIRUS, -3407668, -13434829, new Item.Properties()));
	public static final RegistryObject<Item> SOUL_SURVIVOR = REGISTRY.register("soul_survivor", () -> new SoulSurvivorItem());
	public static final RegistryObject<Item> FLASH_PANOPTICOM_SPAWN_EGG = REGISTRY.register("flash_panopticom_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.FLASH_PANOPTICOM, -13421773, -52429, new Item.Properties()));
	public static final RegistryObject<Item> TERPENE = REGISTRY.register("terpene", () -> new TerpeneItem());
	public static final RegistryObject<Item> LINFOCITA_B_SPAWN_EGG = REGISTRY.register("linfocita_b_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.LINFOCITA_B, -16763905, -16737793, new Item.Properties()));
	public static final RegistryObject<Item> PLASMACELLULA_SPAWN_EGG = REGISTRY.register("plasmacellula_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.PLASMACELLULA, -10092442, -6750055, new Item.Properties()));
	public static final RegistryObject<Item> ANTICORPO_SPAWN_EGG = REGISTRY.register("anticorpo_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.ANTICORPO, -13312, -26317, new Item.Properties()));
	public static final RegistryObject<Item> ASSO_DI_CUORI_DI_VETRO = REGISTRY.register("asso_di_cuori_di_vetro", () -> new AssoDiCuoriDiVetroItem());
	public static final RegistryObject<Item> ESSERE_PERFETTAMENTE_INUTILE_SPAWN_EGG = REGISTRY.register("essere_perfettamente_inutile_spawn_egg",
			() -> new ForgeSpawnEggItem(CumModEntities.ESSERE_PERFETTAMENTE_INUTILE, -10066330, -10066330, new Item.Properties()));
	public static final RegistryObject<Item> LINFOCITA_T_SPAWN_EGG = REGISTRY.register("linfocita_t_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.LINFOCITA_T, -16751104, -16711936, new Item.Properties()));
	public static final RegistryObject<Item> ASSO_DI_FIORI_DI_VETRO = REGISTRY.register("asso_di_fiori_di_vetro", () -> new AssoDiFioriDiVetroItem());
	public static final RegistryObject<Item> FILFH_SPAWN_EGG = REGISTRY.register("filfh_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.FILFH, -13421824, -13434880, new Item.Properties()));
	public static final RegistryObject<Item> FIREBALL_STRAY = REGISTRY.register("fireball_stray", () -> new FireballStrayItem());
	public static final RegistryObject<Item> STRAYS_ARM = REGISTRY.register("strays_arm", () -> new StraysArmItem());
	public static final RegistryObject<Item> BLUE_ORB = REGISTRY.register("blue_orb", () -> new BlueOrbItem());
	public static final RegistryObject<Item> ALT_PIERCER = REGISTRY.register("alt_piercer", () -> new AltPiercerItem());
	public static final RegistryObject<Item> METALLO_ULTRAKILLANTE = block(CumModBlocks.METALLO_ULTRAKILLANTE);
	public static final RegistryObject<Item> LINGOTTO_ULTRAKILLANTE = REGISTRY.register("lingotto_ultrakillante", () -> new LingottoUltrakillanteItem());
	public static final RegistryObject<Item> TAVOLO_BALATRANTE = block(CumModBlocks.TAVOLO_BALATRANTE);
	public static final RegistryObject<Item> JOKER = REGISTRY.register("joker", () -> new JokerItem());
	public static final RegistryObject<Item> FICHE = REGISTRY.register("fiche", () -> new FicheItem());
	public static final RegistryObject<Item> PIETRA_BALATRANTE = block(CumModBlocks.PIETRA_BALATRANTE);
	public static final RegistryObject<Item> ACQUA_DEL_GODO_BUCKET = REGISTRY.register("acqua_del_godo_bucket", () -> new AcquaDelGodoItem());
	public static final RegistryObject<Item> BALATRO_GRASS = block(CumModBlocks.BALATRO_GRASS);
	public static final RegistryObject<Item> BALATRO_DIRT = block(CumModBlocks.BALATRO_DIRT);
	public static final RegistryObject<Item> BALATRO_LOG = block(CumModBlocks.BALATRO_LOG);
	public static final RegistryObject<Item> BALATRO_LEAVES = block(CumModBlocks.BALATRO_LEAVES);
	public static final RegistryObject<Item> CARTA_DI_PIETRA = REGISTRY.register("carta_di_pietra", () -> new CartaDiPietraItem());
	public static final RegistryObject<Item> MOLT = REGISTRY.register("molt", () -> new MoltItem());
	public static final RegistryObject<Item> CIANOGRAFIA = REGISTRY.register("cianografia", () -> new CianografiaItem());
	public static final RegistryObject<Item> SCHEGGIA_DI_PIETRA_BALATRANTE = REGISTRY.register("scheggia_di_pietra_balatrante", () -> new ScheggiaDiPietraBalatranteItem());
	public static final RegistryObject<Item> PER_ATTPED = block(CumModBlocks.PER_ATTPED);
	public static final RegistryObject<Item> IL_FU_MATTIA_PASCAL_DISCO = REGISTRY.register("il_fu_mattia_pascal_disco", () -> new IlFuMattiaPascalDiscoItem());
	public static final RegistryObject<Item> ULTRAKILLANTE_ORE = block(CumModBlocks.ULTRAKILLANTE_ORE);
	public static final RegistryObject<Item> ULTRAKILLANTE_BLOCK = block(CumModBlocks.ULTRAKILLANTE_BLOCK);
	public static final RegistryObject<Item> ARMATURA_ULTRAKILLANTE_CHESTPLATE = REGISTRY.register("armatura_ultrakillante_chestplate", () -> new ArmaturaUltrakillanteItem.Chestplate());
	public static final RegistryObject<Item> ARMATURA_ULTRAKILLANTE_LEGGINGS = REGISTRY.register("armatura_ultrakillante_leggings", () -> new ArmaturaUltrakillanteItem.Leggings());
	public static final RegistryObject<Item> OLIVIA_SPAWN_EGG = REGISTRY.register("olivia_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.OLIVIA, -10092442, -52225, new Item.Properties()));
	public static final RegistryObject<Item> BALATRO_PLANT = block(CumModBlocks.BALATRO_PLANT);
	public static final RegistryObject<Item> PAPERON_DE_PAPERONI_SPAWN_EGG = REGISTRY.register("paperon_de_paperoni_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.PAPERON_DE_PAPERONI, -3407872, -16317896, new Item.Properties()));
	public static final RegistryObject<Item> BASTONE_PAPERONE = REGISTRY.register("bastone_paperone", () -> new BastonePaperoneItem());
	public static final RegistryObject<Item> MATTIA_PASCAL_SPAWN_EGG = REGISTRY.register("mattia_pascal_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.MATTIA_PASCAL, -16186038, -10092544, new Item.Properties()));
	public static final RegistryObject<Item> MANOSCRITTO_DI_IGIENE = block(CumModBlocks.MANOSCRITTO_DI_IGIENE);
	public static final RegistryObject<Item> ADRIANO_MEIS_SPAWN_EGG = REGISTRY.register("adriano_meis_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.ADRIANO_MEIS, -16186038, -10092544, new Item.Properties()));
	public static final RegistryObject<Item> IL_FU_MATTIA_PASCAL_2_SPAWN_EGG = REGISTRY.register("il_fu_mattia_pascal_2_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.IL_FU_MATTIA_PASCAL_2, -16186038, -10092544, new Item.Properties()));
	public static final RegistryObject<Item> CIANOGRAFIA_NEGATIVA = REGISTRY.register("cianografia_negativa", () -> new CianografiaNegativaItem());
	public static final RegistryObject<Item> DISC_CHAOS = REGISTRY.register("disc_chaos", () -> new DiscChaosItem());
	public static final RegistryObject<Item> DISC_ORDER_1 = REGISTRY.register("disc_order_1", () -> new DiscOrder1Item());
	public static final RegistryObject<Item> DISC_ORDER_2 = REGISTRY.register("disc_order_2", () -> new DiscOrder2Item());
	public static final RegistryObject<Item> BLOCCO_ULTRARIATTIVANTE = block(CumModBlocks.BLOCCO_ULTRARIATTIVANTE);
	public static final RegistryObject<Item> BLOCCO_DI_CARNE_PANOPTICA = block(CumModBlocks.BLOCCO_DI_CARNE_PANOPTICA);
	public static final RegistryObject<Item> DISC_PANDEMONIUM = REGISTRY.register("disc_pandemonium", () -> new DiscPandemoniumItem());
	public static final RegistryObject<Item> DISC_WAR_1 = REGISTRY.register("disc_war_1", () -> new DiscWar1Item());
	public static final RegistryObject<Item> DISC_WAR_2 = REGISTRY.register("disc_war_2", () -> new DiscWar2Item());
	public static final RegistryObject<Item> OLIVIA_BLOCK = block(CumModBlocks.OLIVIA_BLOCK);
	public static final RegistryObject<Item> FILFH_ERR_SPAWN_EGG = REGISTRY.register("filfh_err_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.FILFH_ERR, -65383, -6684928, new Item.Properties()));
	public static final RegistryObject<Item> PERKEO = REGISTRY.register("perkeo", () -> new PerkeoItem());
	public static final RegistryObject<Item> PERKEO_NEGATIVO = REGISTRY.register("perkeo_negativo", () -> new PerkeoNegativoItem());
	public static final RegistryObject<Item> GABRIEL_SPAWN_EGG = REGISTRY.register("gabriel_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.GABRIEL, -3355648, -16711681, new Item.Properties()));
	public static final RegistryObject<Item> SPADA_GABRIELLANTE = REGISTRY.register("spada_gabriellante", () -> new SpadaGabriellanteItem());
	public static final RegistryObject<Item> MALICIOUS_FACE_SPAWN_EGG = REGISTRY.register("malicious_face_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.MALICIOUS_FACE, -10066330, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> CUBO = REGISTRY.register("cubo", () -> new CuboItem());
	public static final RegistryObject<Item> PROSECCO = REGISTRY.register("prosecco", () -> new ProseccoItem());
	public static final RegistryObject<Item> STRAY_SPAWN_EGG = REGISTRY.register("stray_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.STRAY, -52429, -6750208, new Item.Properties()));
	public static final RegistryObject<Item> DUE_DI_PICCHIE = REGISTRY.register("due_di_picchie", () -> new DueDiPicchieItem());
	public static final RegistryObject<Item> DUE_DI_CUORI = REGISTRY.register("due_di_cuori", () -> new DueDiCuoriItem());
	public static final RegistryObject<Item> DUE_DI_FIORI = REGISTRY.register("due_di_fiori", () -> new DueDiFioriItem());
	public static final RegistryObject<Item> DUE_DI_QUADRI = REGISTRY.register("due_di_quadri", () -> new DueDiQuadriItem());
	public static final RegistryObject<Item> TRE_DI_PICCHIE = REGISTRY.register("tre_di_picchie", () -> new TreDiPicchieItem());
	public static final RegistryObject<Item> TRE_DI_CUORI = REGISTRY.register("tre_di_cuori", () -> new TreDiCuoriItem());
	public static final RegistryObject<Item> TRE_DI_FIORI = REGISTRY.register("tre_di_fiori", () -> new TreDiFioriItem());
	public static final RegistryObject<Item> TRE_DI_QUADRI = REGISTRY.register("tre_di_quadri", () -> new TreDiQuadriItem());
	public static final RegistryObject<Item> QU_DI_PICCHIE = REGISTRY.register("qu_di_picchie", () -> new QuDiPicchieItem());
	public static final RegistryObject<Item> QU_DI_CUORI = REGISTRY.register("qu_di_cuori", () -> new QuDiCuoriItem());
	public static final RegistryObject<Item> QU_DI_FIORI = REGISTRY.register("qu_di_fiori", () -> new QuDiFioriItem());
	public static final RegistryObject<Item> QU_DI_QUADRI = REGISTRY.register("qu_di_quadri", () -> new QuDiQuadriItem());
	public static final RegistryObject<Item> CIN_DI_PICCHIE = REGISTRY.register("cin_di_picchie", () -> new CinDiPicchieItem());
	public static final RegistryObject<Item> CIN_DI_CUORI = REGISTRY.register("cin_di_cuori", () -> new CinDiCuoriItem());
	public static final RegistryObject<Item> CIN_DI_FIORI = REGISTRY.register("cin_di_fiori", () -> new CinDiFioriItem());
	public static final RegistryObject<Item> CIN_DI_QUADRI = REGISTRY.register("cin_di_quadri", () -> new CinDiQuadriItem());
	public static final RegistryObject<Item> SEI_DI_PICCHIE = REGISTRY.register("sei_di_picchie", () -> new SeiDiPicchieItem());
	public static final RegistryObject<Item> SEI_DI_CUORI = REGISTRY.register("sei_di_cuori", () -> new SeiDiCuoriItem());
	public static final RegistryObject<Item> SEI_DI_FIORI = REGISTRY.register("sei_di_fiori", () -> new SeiDiFioriItem());
	public static final RegistryObject<Item> SEI_DI_QUADRI = REGISTRY.register("sei_di_quadri", () -> new SeiDiQuadriItem());
	public static final RegistryObject<Item> SETTE_DI_PICCHIE = REGISTRY.register("sette_di_picchie", () -> new SetteDiPicchieItem());
	public static final RegistryObject<Item> SETTE_DI_CUORI = REGISTRY.register("sette_di_cuori", () -> new SetteDiCuoriItem());
	public static final RegistryObject<Item> SETTE_DI_FIORI = REGISTRY.register("sette_di_fiori", () -> new SetteDiFioriItem());
	public static final RegistryObject<Item> SETTE_DI_QUADRI = REGISTRY.register("sette_di_quadri", () -> new SetteDiQuadriItem());
	public static final RegistryObject<Item> OTTO_DI_PICCHIE = REGISTRY.register("otto_di_picchie", () -> new OttoDiPicchieItem());
	public static final RegistryObject<Item> OTTO_DI_CUORI = REGISTRY.register("otto_di_cuori", () -> new OttoDiCuoriItem());
	public static final RegistryObject<Item> OTTO_DI_FIORI = REGISTRY.register("otto_di_fiori", () -> new OttoDiFioriItem());
	public static final RegistryObject<Item> OTTO_DI_QUADRI = REGISTRY.register("otto_di_quadri", () -> new OttoDiQuadriItem());
	public static final RegistryObject<Item> NOVE_DI_PICCHIE = REGISTRY.register("nove_di_picchie", () -> new NoveDiPicchieItem());
	public static final RegistryObject<Item> NOVE_DI_CUORI = REGISTRY.register("nove_di_cuori", () -> new NoveDiCuoriItem());
	public static final RegistryObject<Item> NOVE_DI_FIORI = REGISTRY.register("nove_di_fiori", () -> new NoveDiFioriItem());
	public static final RegistryObject<Item> NOVE_DI_QUADRI = REGISTRY.register("nove_di_quadri", () -> new NoveDiQuadriItem());
	public static final RegistryObject<Item> DIECI_DI_PICCHIE = REGISTRY.register("dieci_di_picchie", () -> new DieciDiPicchieItem());
	public static final RegistryObject<Item> DIECI_DI_CUORI = REGISTRY.register("dieci_di_cuori", () -> new DieciDiCuoriItem());
	public static final RegistryObject<Item> DIECI_DI_FIORI = REGISTRY.register("dieci_di_fiori", () -> new DieciDiFioriItem());
	public static final RegistryObject<Item> DIECI_DI_QUADRI = REGISTRY.register("dieci_di_quadri", () -> new DieciDiQuadriItem());
	public static final RegistryObject<Item> QUESTOEILGODO = REGISTRY.register("questoeilgodo", () -> new QUESTOEILGODOItem());
	public static final RegistryObject<Item> BLOOD_BUCKET = REGISTRY.register("blood_bucket", () -> new BloodItem());
	public static final RegistryObject<Item> TECNOLOGIA_V_1NANTE = REGISTRY.register("tecnologia_v_1nante", () -> new TecnologiaV1nanteItem());
	public static final RegistryObject<Item> DISPOSITIVO_TELETRASPORTANTE = REGISTRY.register("dispositivo_teletrasportante", () -> new DispositivoTeletrasportanteItem());
	public static final RegistryObject<Item> PANE_INTEGRALE = REGISTRY.register("pane_integrale", () -> new PaneIntegraleItem());
	public static final RegistryObject<Item> BLOCCO_INTEGRALE = block(CumModBlocks.BLOCCO_INTEGRALE);
	public static final RegistryObject<Item> BLOCCO_DERIVANTE = block(CumModBlocks.BLOCCO_DERIVANTE);
	public static final RegistryObject<Item> PANE_DERIVANTE = REGISTRY.register("pane_derivante", () -> new PaneDerivanteItem());
	public static final RegistryObject<Item> QUESTOEILGODO_NEGATIVO = REGISTRY.register("questoeilgodo_negativo", () -> new QUESTOEILGODONegativoItem());
	public static final RegistryObject<Item> STELLA_PERICOLOSA = REGISTRY.register("stella_pericolosa", () -> new StellaPericolosaItem());
	public static final RegistryObject<Item> IMPALATORE = block(CumModBlocks.IMPALATORE);
	public static final RegistryObject<Item> CLONATORE = REGISTRY.register("clonatore", () -> new ClonatoreItem());
	public static final RegistryObject<Item> MACCHINA_DEL_TEMPO = REGISTRY.register("macchina_del_tempo", () -> new MacchinaDelTempoItem());
	public static final RegistryObject<Item> UOMO_PRIMITIVO_SPAWN_EGG = REGISTRY.register("uomo_primitivo_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.UOMO_PRIMITIVO, -39424, -39322, new Item.Properties()));
	public static final RegistryObject<Item> LUNA_DEL_GODO = REGISTRY.register("luna_del_godo", () -> new LunaDelGodoItem());
	public static final RegistryObject<Item> SPADA_LUNARE_1 = REGISTRY.register("spada_lunare_1", () -> new SpadaLunare1Item());
	public static final RegistryObject<Item> SPADA_LUNARE_2 = REGISTRY.register("spada_lunare_2", () -> new SpadaLunare2Item());
	public static final RegistryObject<Item> BOLOGNESE_CON_L_UOVO = REGISTRY.register("bolognese_con_l_uovo", () -> new BologneseConLUovoItem());
	public static final RegistryObject<Item> SPADA_LUNARE_3 = REGISTRY.register("spada_lunare_3", () -> new SpadaLunare3Item());
	public static final RegistryObject<Item> ARMATURA_LUNARE_HELMET = REGISTRY.register("armatura_lunare_helmet", () -> new ArmaturaLunareItem.Helmet());
	public static final RegistryObject<Item> ARMATURA_LUNARE_CHESTPLATE = REGISTRY.register("armatura_lunare_chestplate", () -> new ArmaturaLunareItem.Chestplate());
	public static final RegistryObject<Item> ARMATURA_LUNARE_LEGGINGS = REGISTRY.register("armatura_lunare_leggings", () -> new ArmaturaLunareItem.Leggings());
	public static final RegistryObject<Item> ARMATURA_LUNARE_BOOTS = REGISTRY.register("armatura_lunare_boots", () -> new ArmaturaLunareItem.Boots());
	public static final RegistryObject<Item> PER_INV_1_SPAWN_EGG = REGISTRY.register("per_inv_1_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.PER_INV_1, -13421773, -3355648, new Item.Properties()));
	public static final RegistryObject<Item> IMPENETRAZIONE_HELMET = REGISTRY.register("impenetrazione_helmet", () -> new IMPENETRAZIONEItem.Helmet());
	public static final RegistryObject<Item> IMPENETRAZIONE_CHESTPLATE = REGISTRY.register("impenetrazione_chestplate", () -> new IMPENETRAZIONEItem.Chestplate());
	public static final RegistryObject<Item> IMPENETRAZIONE_LEGGINGS = REGISTRY.register("impenetrazione_leggings", () -> new IMPENETRAZIONEItem.Leggings());
	public static final RegistryObject<Item> IMPENETRAZIONE_BOOTS = REGISTRY.register("impenetrazione_boots", () -> new IMPENETRAZIONEItem.Boots());
	public static final RegistryObject<Item> NERO_COLTELLO = REGISTRY.register("nero_coltello", () -> new NeroColtelloItem());
	public static final RegistryObject<Item> ASSASSINA_DEI_NERI_COLTELLI_SPAWN_EGG = REGISTRY.register("assassina_dei_neri_coltelli_spawn_egg",
			() -> new ForgeSpawnEggItem(CumModEntities.ASSASSINA_DEI_NERI_COLTELLI, -16777165, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> BLOCCO_LUNARE = block(CumModBlocks.BLOCCO_LUNARE);
	public static final RegistryObject<Item> IMPENETRABLE_TEMPLATE = REGISTRY.register("impenetrable_template", () -> new ImpenetrableTemplateItem());
	public static final RegistryObject<Item> IMPENETRABILE_INTERMEDIO = REGISTRY.register("impenetrabile_intermedio", () -> new ImpenetrabileIntermedioItem());
	public static final RegistryObject<Item> TUTA_LEGGINGS = REGISTRY.register("tuta_leggings", () -> new TutaItem.Leggings());
	public static final RegistryObject<Item> PER_INV_2_SPAWN_EGG = REGISTRY.register("per_inv_2_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.PER_INV_2, -13421773, -8619008, new Item.Properties()));
	public static final RegistryObject<Item> PER_INV_3_SPAWN_EGG = REGISTRY.register("per_inv_3_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.PER_INV_3, -13421773, -3382016, new Item.Properties()));
	public static final RegistryObject<Item> SPADA_LUNARE_4 = REGISTRY.register("spada_lunare_4", () -> new SpadaLunare4Item());
	public static final RegistryObject<Item> STIVALI_IMMOVIBILI_BOOTS = REGISTRY.register("stivali_immovibili_boots", () -> new StivaliImmovibiliItem.Boots());
	public static final RegistryObject<Item> DNA = REGISTRY.register("dna", () -> new DNAItem());
	public static final RegistryObject<Item> GEL_DI_AGAROSIO_BUCKET = REGISTRY.register("gel_di_agarosio_bucket", () -> new GelDiAgarosioItem());
	public static final RegistryObject<Item> MATRICE = block(CumModBlocks.MATRICE);
	public static final RegistryObject<Item> FRIGO = block(CumModBlocks.FRIGO);
	public static final RegistryObject<Item> MICROPIPETTA = REGISTRY.register("micropipetta", () -> new MicropipettaItem());
	public static final RegistryObject<Item> PUNTALE = REGISTRY.register("puntale", () -> new PuntaleItem());
	public static final RegistryObject<Item> PUNTALE_CONTAMINATO = REGISTRY.register("puntale_contaminato", () -> new PuntaleContaminatoItem());
	public static final RegistryObject<Item> ECO_RI = REGISTRY.register("eco_ri", () -> new EcoRIItem());
	public static final RegistryObject<Item> PROVETTA = block(CumModBlocks.PROVETTA);
	public static final RegistryObject<Item> PROVETTA_CON_LIQUIDO = block(CumModBlocks.PROVETTA_CON_LIQUIDO);
	public static final RegistryObject<Item> PROVETTA_CON_DNA_FRAMMENTATO = block(CumModBlocks.PROVETTA_CON_DNA_FRAMMENTATO);
	public static final RegistryObject<Item> CIPOLLA_MARCIA = REGISTRY.register("cipolla_marcia", () -> new CipollaMarciaItem());
	public static final RegistryObject<Item> PUNTALENEGATIVO = REGISTRY.register("puntalenegativo", () -> new PuntalenegativoItem());
	public static final RegistryObject<Item> PUNTALE_CONTAMINATO_NEGATIVO = REGISTRY.register("puntale_contaminato_negativo", () -> new PuntaleContaminatoNegativoItem());
	public static final RegistryObject<Item> DNA_FRAMMENTATO = REGISTRY.register("dna_frammentato", () -> new DNAFrammentatoItem());
	public static final RegistryObject<Item> CAMPIONE_DI_DNA_FRAMMENTATO = REGISTRY.register("campione_di_dna_frammentato", () -> new CampioneDiDNAFrammentatoItem());
	public static final RegistryObject<Item> CAMPIONE_DI_DNA = REGISTRY.register("campione_di_dna", () -> new CampioneDiDNAItem());
	public static final RegistryObject<Item> PEASHOOTER_SPAWN_EGG = REGISTRY.register("peashooter_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.PEASHOOTER, -16764160, -16751104, new Item.Properties()));
	public static final RegistryObject<Item> DAVE_SPAWN_EGG = REGISTRY.register("dave_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.DAVE, -6737152, -6710887, new Item.Properties()));
	public static final RegistryObject<Item> CONO_ITEM = REGISTRY.register("cono_item", () -> new ConoItemItem());
	public static final RegistryObject<Item> CONO_BLOCK = block(CumModBlocks.CONO_BLOCK);
	public static final RegistryObject<Item> NOCCIOLINA_SPAWN_EGG = REGISTRY.register("nocciolina_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.NOCCIOLINA, -10079488, -6724096, new Item.Properties()));
	public static final RegistryObject<Item> GIRASOLE_SPAWN_EGG = REGISTRY.register("girasole_spawn_egg", () -> new ForgeSpawnEggItem(CumModEntities.GIRASOLE, -12968704, -1777408, new Item.Properties()));
	public static final RegistryObject<Item> FRENZIED_CUM = REGISTRY.register("frenzied_cum", () -> new FrenziedCumItem());
	public static final RegistryObject<Item> PENE_DELLA_FRENESIA = REGISTRY.register("pene_della_frenesia", () -> new PeneDellaFrenesiaItem());
	public static final RegistryObject<Item> GENESGUN = REGISTRY.register("genesgun", () -> new GenesgunItem());
	public static final RegistryObject<Item> PALLOTTOLADORO = REGISTRY.register("pallottoladoro", () -> new PallottoladoroItem());
	public static final RegistryObject<Item> PLASMIDEVUOTO = REGISTRY.register("plasmidevuoto", () -> new PlasmidevuotoItem());
	public static final RegistryObject<Item> MANO_DI_MALENIA = REGISTRY.register("mano_di_malenia", () -> new ManoDiMaleniaItem());
	public static final RegistryObject<Item> MALENIA_BLADE_OF_MIQUELLA_SPAWN_EGG = REGISTRY.register("malenia_blade_of_miquella_spawn_egg",
			() -> new ForgeSpawnEggItem(CumModEntities.MALENIA_BLADE_OF_MIQUELLA, -10066432, -10092544, new Item.Properties()));
	public static final RegistryObject<Item> GENEAMPICILLINA = REGISTRY.register("geneampicillina", () -> new GeneampicillinaItem());
	public static final RegistryObject<Item> GENETETRACILLINA = REGISTRY.register("genetetracillina", () -> new GenetetracillinaItem());
	public static final RegistryObject<Item> PLASMIDEAMP = REGISTRY.register("plasmideamp", () -> new PlasmideampItem());
	public static final RegistryObject<Item> PLASMIDECONTET = REGISTRY.register("plasmidecontet", () -> new PlasmidecontetItem());
	public static final RegistryObject<Item> PBR_322 = REGISTRY.register("pbr_322", () -> new PBR32Item());
	public static final RegistryObject<Item> ARMATURADELSANGUE_BOOTS = REGISTRY.register("armaturadelsangue_boots", () -> new ArmaturadelsangueItem.Boots());
	public static final RegistryObject<Item> SLAB_DI_SANGUE = block(CumModBlocks.SLAB_DI_SANGUE);

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
